import nbformat as nbf
nb = nbf.v4.new_notebook()
nb.metadata = {"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"name":"python","version":"3.10.0"}}
C = []
M = nbf.v4.new_markdown_cell
K = nbf.v4.new_code_cell

C.append(M('# Module 1: 基石算子——代码实战\n\n> 从广播机制到激活函数，从归一化到手算梯度——用代码验证每一个概念。\n\n本 Notebook 覆盖 Module 1 的全部核心概念，每个 Section 对应文档中的一个章节。'))

C.append(M('## 0. 环境准备'))
C.append(M('导入所有需要的库。`torch` 做张量运算，`numpy` 辅助数据处理，`matplotlib` 画图。'))
C.append(K('import torch\nimport torch.nn as nn\nimport torch.nn.functional as F\nimport numpy as np\nimport matplotlib.pyplot as plt\n\nplt.rcParams["font.sans-serif"] = ["Microsoft YaHei", "SimHei", "DejaVu Sans"]\nplt.rcParams["axes.unicode_minus"] = False\nplt.rcParams["font.size"] = 12\nplt.rcParams["figure.figsize"] = (10, 5)\nprint(f"PyTorch: {torch.__version__}")\nprint(f"NumPy:   {np.__version__}")\nprint("Ready!")'))

C.append(M('---\n## 1. 数学运算\n\n### 1.1 七种基本二元运算\n\n两个张量逐元素做运算——这是所有复杂操作的最小可分解单元。Add 做残差连接，Mul 做门控，Pow 做 RoPE 频率计算。'))
C.append(K('a = torch.tensor([1.0, 2.0, 3.0])\nb = torch.tensor([4.0, 5.0, 6.0])\n\nprint(f"a = {a.tolist()}")\nprint(f"b = {b.tolist()}")\nprint()\nprint(f"a + b  = {(a + b).tolist()}     # 残差连接")\nprint(f"a - b  = {(a - b).tolist()}     # 差值")\nprint(f"a * b  = {(a * b).tolist()}     # 门控: gate * value")\nprint(f"a / b  = {(a / b).tolist()}     # 缩放")\nprint(f"a ** 2 = {(a ** 2).tolist()}   # 幂: RoPE")\nprint(f"max(a,b) = {torch.maximum(a, b).tolist()}")'))

C.append(M('### 1.2 广播机制——逐维度对齐\n\n规则：从最后一个维度向前比较，每个维度要么相等，要么其中一个为 1。'))
C.append(M('**能广播的例子：**'))
C.append(K('print("=" * 50)\nprint("能广播的例子:")\nprint()\nx = torch.ones(3, 1, 4)\ny = torch.ones(1, 5, 4) * 2\nz = x + y\nprint(f"[3,1,4] + [1,5,4] -> shape = {z.shape}  (预期 [3,5,4])")\nx = torch.ones(2, 3)\ny = torch.tensor([10.0, 20.0, 30.0])\nz = x + y\nprint(f"[2,3] + [3] -> shape = {z.shape}   (预期 [2,3])")\nprint(f"z =\\n{z}")\nprint()\ngamma = torch.tensor([1.0, 2.0, 3.0])\nx = torch.ones(2, 3, 4, 4)\nresult = x * gamma.view(1, 3, 1, 1)\nprint(f"BN风格: gamma[3] * x[2,3,4,4] -> shape = {result.shape}")\nprint(f"  ch0 all={result[0,0,0,0]:.0f}, ch1 all={result[0,1,0,0]:.0f}, ch2 all={result[0,2,0,0]:.0f}")'))

C.append(M('**不能广播的例子：**'))
C.append(K('print("=" * 50)\nprint("不能广播的例子:")\nprint()\ntry:\n    x = torch.ones(3, 4)\n    y = torch.ones(2, 4)\n    z = x + y\nexcept RuntimeError as e:\n    print("[3,4] + [2,4]")\n    print("  -> 轴0: 3 vs 2, 都不为1, 无法广播")\n    print()\ntry:\n    x = torch.ones(2, 3, 4)\n    y = torch.ones(5, 4)\n    z = x + y\nexcept RuntimeError as e:\n    print("[2,3,4] + [5,4]")\n    print("  -> 从后对齐, 轴1: 3 vs 5, 都不为1")'))

C.append(M('### 1.3 归约运算\n\n沿指定维度将多个值聚合为一个。GlobalAvgPool 本质是 Mean 归约，Softmax 的分母是 Sum 归约。'))
C.append(K('x = torch.tensor([[1.0, 2.0, 3.0, 4.0],\n                  [5.0, 6.0, 7.0, 8.0]])\nprint(f"原始 [{x.shape[0]}x{x.shape[1]}]:\\n{x}\\n")\nprint(f"Sum(dim=1)   = {x.sum(dim=1).tolist()}       # 每行求和")\nprint(f"Mean(dim=1)  = {x.mean(dim=1).tolist()}      # 每行平均 (GAP)")\nprint(f"Max(dim=1)   = {x.max(dim=1).values.tolist()} # 每行最大值")\nprint(f"\\n全归约:")\nprint(f"  全局 Sum  = {x.sum().item()}")\nprint(f"  全局 Mean = {x.mean().item():.4f}")'))

C.append(M('---\n## 2. 激活函数\n\n激活函数是神经网络的灵魂——没有它，100层线性变换 = 1层。注意观察负值区的行为差异：ReLU 直接归零，GELU/Swish 保留微弱信号。这就是"死亡 ReLU"的根源。'))
C.append(K('x = torch.linspace(-4, 4, 500)\nacts = {\n    "ReLU":F.relu(x), "LeakyReLU":F.leaky_relu(x,0.1),\n    "GELU":F.gelu(x), "Swish/SiLU":F.silu(x),\n    "Sigmoid":torch.sigmoid(x), "Tanh":torch.tanh(x)\n}\nfig, axes = plt.subplots(2, 3, figsize=(16, 9))\nfor ax, (name, y) in zip(axes.flatten(), acts.items()):\n    ax.plot(x.numpy(), y.numpy(), lw=2, color="#2196F3")\n    ax.axhline(y=0, color="gray", ls="--", alpha=0.5)\n    ax.axvline(x=0, color="gray", ls="--", alpha=0.5)\n    ax.set_title(name, fontsize=14, fontweight="bold")\n    ax.set_xlabel("x"); ax.set_ylabel("f(x)"); ax.grid(True, alpha=0.3)\nplt.suptitle("Activation Functions", fontsize=18, fontweight="bold", y=1.02)\nplt.tight_layout(); plt.show()'))

C.append(M('**ReLU vs GELU vs Swish 同图对比——聚焦负值区：**'))
C.append(K('x = torch.linspace(-3, 3, 300)\nplt.figure(figsize=(12, 5))\nplt.plot(x.numpy(), F.relu(x).numpy(), lw=2, label="ReLU (hard cutoff)")\nplt.plot(x.numpy(), F.gelu(x).numpy(), lw=2, label="GELU (probabilistic)")\nplt.plot(x.numpy(), F.silu(x).numpy(), lw=2, label="Swish/SiLU (self-gating)")\nplt.axhline(y=0, color="gray", ls="--", alpha=0.5)\nplt.axvline(x=0, color="gray", ls="--", alpha=0.5)\nplt.xlabel("x", fontsize=13); plt.ylabel("f(x)", fontsize=13)\nplt.title("ReLU vs GELU vs Swish", fontsize=15, fontweight="bold")\nplt.legend(fontsize=12, loc="upper left"); plt.grid(True, alpha=0.3)\nplt.tight_layout(); plt.show()\n\nprint("负值区行为对比:")\nfor val in [-3, -1, 0]:\n    r = F.relu(torch.tensor(float(val))).item()\n    g = F.gelu(torch.tensor(float(val))).item()\n    s = F.silu(torch.tensor(float(val))).item()\n    print(f"  x={val:2d}: ReLU={r:6.3f}, GELU={g:6.3f}, Swish={s:6.3f}")\nprint()\nprint("关键: x=-3 时 ReLU=0 (梯度=0!), 但 Swish=-0.14 (仍有梯度)")'))

C.append(M('### 2.1 Sigmoid vs Softmax\n\nSigmoid: 每个元素独立判断 (可以多个高概率)。Softmax: 整个向量联合决策 (概率和=1, 只能选一个)。'))
C.append(K('logits = torch.tensor([2.0, 1.0, 0.5, -1.0])\nsig = torch.sigmoid(logits)\nprint(f"原始值:  {logits.tolist()}")\nprint(f"Sigmoid: {[f\"{x:.3f}\" for x in sig.tolist()]}")\nprint(f"  -> 各值独立在(0,1), 总和={sig.sum():.3f} (不是1!)")\nsfm = F.softmax(logits, dim=0)\nprint(f"Softmax: {[f\"{x:.3f}\" for x in sfm.tolist()]}")\nprint(f"  -> 各值在(0,1), 总和={sfm.sum():.3f} (一定是1)")\nprint()\ntemps = [0.5, 1.0, 2.0, 5.0]\nfig, axes = plt.subplots(1, 4, figsize=(16, 3))\ncolors = ["#FF5722","#2196F3","#4CAF50","#FFC107"]\nfor ax, T in zip(axes, temps):\n    probs = F.softmax(logits / T, dim=0)\n    ax.bar(range(4), probs.numpy(), color=colors)\n    ax.set_title(f"T={T}", fontweight="bold"); ax.set_ylim(0, 1)\nplt.suptitle("Temperature 对 Softmax 的影响", fontsize=14, fontweight="bold")\nplt.tight_layout(); plt.show()\nprint("T<1: 更尖锐 | T=1: 原始 | T>1: 更平滑")'))

C.append(M('### 2.2 SwiGLU——现代 LLM MLP 的核心\n\nSwiGLU = Swish(x.W_gate) * (x.W_up) . W_down。gate 产生门控信号，up 携带信息，相乘 = 选择性放行。中间维度 3x hidden (不是 4x)，因为比标准 FFN 多一个权重矩阵。'))
C.append(K('hd, inter = 8, 24\nx = torch.randn(1, hd)\nWg, Wu, Wd = torch.randn(hd, inter), torch.randn(hd, inter), torch.randn(inter, hd)\ngate = F.silu(x @ Wg)\nup = x @ Wu\ngated = gate * up\noutput = gated @ Wd\nprint(f"输入:  {x.shape}")\nprint(f"gate:  Swish(x.Wg) -> {gate.shape}   (门控信号)")\nprint(f"up:    x.Wu        -> {up.shape}     (信息流)")\nprint(f"gated: gate * up   -> {gated.shape}   (选择性放行!)")\nprint(f"output:gated.Wd    -> {output.shape}  (最终输出)")\nprint(f"\\n门控信号统计: min={gate.min():.2f}, max={gate.max():.2f}, mean={gate.mean():.2f}")\npct = ((gate > 0.01) & (gate < 0.99)).float().mean() * 100\nprint(f"{pct:.0f}% 处于部分门控 (0.01~0.99) — 软调节而非硬开关")'))

C.append(M('---\n## 3. 归一化——手写 BN / LN / RMSNorm\n\n- BatchNorm: 跨 (N,H,W) 统计，每通道独立，CNN 专用\n- LayerNorm: 跨 (C,H,W) 统计，每样本独立，Transformer 专用\n- RMSNorm: LayerNorm 精简版，去掉均值减法 + beta，省 30% 计算，现代 LLM 标配'))
C.append(K('def my_bn(x, g, b, eps=1e-5):\n    m = x.mean(dim=(0,2,3), keepdim=True)\n    v = x.var(dim=(0,2,3), keepdim=True, unbiased=False)\n    return g.view(1,-1,1,1)*(x-m)/torch.sqrt(v+eps)+b.view(1,-1,1,1)\n\ndef my_ln(x, g, b, eps=1e-5):\n    m = x.mean(dim=(1,2,3), keepdim=True)\n    v = x.var(dim=(1,2,3), keepdim=True, unbiased=False)\n    return g.view(1,-1,1,1)*(x-m)/torch.sqrt(v+eps)+b.view(1,-1,1,1)\n\ndef my_rms(x, g, eps=1e-6):\n    r = torch.sqrt(torch.mean(x**2, dim=-1, keepdim=True)+eps)\n    return x/r*g\n\nx = torch.randn(2,3,4,4)\ng, b = torch.ones(3), torch.zeros(3)\nprint(f"BN  vs PyTorch: {(my_bn(x,g,b)-F.batch_norm(x,torch.zeros(3),torch.ones(3),training=True)).abs().max():.2e}")\nprint(f"LN  vs PyTorch: {(my_ln(x,g,b)-F.layer_norm(x,[3,4,4],weight=g,bias=b)).abs().max():.2e}")\nxs = torch.randn(2,10,64)\nr = my_rms(xs, torch.ones(64))\nprint(f"RMS output: {r.shape}, mean~{r.mean():.4f}")\nprint("全部验证通过! 误差 < 1e-6")'))

C.append(M('**可视化：归一化前后分布变化**'))
C.append(K('xr = torch.randn(1000)*3+2\nxl = (xr-xr.mean())/xr.std()\nxrm = xr/torch.sqrt(torch.mean(xr**2))\nfig, axes = plt.subplots(1,3,figsize=(15,3))\naxes[0].hist(xr.numpy(),50,color="#FF5722",alpha=0.7)\naxes[0].set_title(f"Original: mean={xr.mean():.2f}, std={xr.std():.2f}")\naxes[1].hist(xl.numpy(),50,color="#2196F3",alpha=0.7)\naxes[1].set_title(f"LayerNorm: mean={xl.mean():.2f}, std={xl.std():.2f}")\naxes[2].hist(xrm.numpy(),50,color="#4CAF50",alpha=0.7)\naxes[2].set_title(f"RMSNorm: RMS~{torch.sqrt(torch.mean(xrm**2)):.2f}")\nplt.suptitle("Normalization Effect",fontsize=14,fontweight="bold")\nplt.tight_layout(); plt.show()'))

C.append(M('---\n## 4. 梯度与反向传播——手算验证\n\n手动 SGD：Loss = (wx - target)^2, 梯度 = 2(wx - target) * x。和 PyTorch autograd 对比。'))
C.append(K('w = torch.tensor([0.0]); x = torch.tensor([2.0]); tgt = torch.tensor([3.0]); lr = 0.1\nhw, hl = [], []\nprint("手动 SGD (手算梯度):")\nprint(f"  初始: w={w.item():.4f}, 最优 w = {tgt.item()/x.item():.1f}")\nprint()\nfor s in range(5):\n    yp = w*x; loss = (yp-tgt)**2; grad = 2*(yp-tgt)*x\n    w = w-lr*grad; hw.append(w.item()); hl.append(loss.item())\n    print(f"  Step{s+1}: w={w.item():.4f}, loss={loss.item():.4f}, grad={grad.item():.4f}")\nprint(f"\\n  收敛: w={w.item():.4f} (理论最优 1.5)")'))

C.append(K('w2 = torch.tensor([0.0], requires_grad=True)\nopt = torch.optim.SGD([w2], lr=0.1)\nprint("PyTorch autograd:")\nfor s in range(5):\n    loss = (w2*x-tgt)**2; opt.zero_grad(); loss.backward(); opt.step()\n    print(f"  Step{s+1}: w={w2.item():.4f}, loss={loss.item():.4f}")\nfig,(ax1,ax2)=plt.subplots(1,2,figsize=(12,3.5))\nax1.plot(hw,"o-",lw=2,color="#2196F3",markersize=8)\nax1.axhline(y=1.5,color="red",ls="--",label="Optimal w=1.5")\nax1.set_xlabel("Step"); ax1.set_ylabel("w"); ax1.set_title("Convergence")\nax1.legend(); ax1.grid(True,alpha=0.3)\nax2.plot(hl,"o-",lw=2,color="#FF5722",markersize=8)\nax2.set_xlabel("Step"); ax2.set_ylabel("Loss"); ax2.set_title("Loss")\nax2.grid(True,alpha=0.3)\nplt.tight_layout(); plt.show()\nprint("手算与 autograd 完全一致!")'))

C.append(M('### 4.1 死亡 ReLU 实验\n\n输入全是负值时，ReLU 梯度归零——前面的层收不到任何学习信号。Swish 保留微小梯度，神经元不会"死"。'))
C.append(K('torch.manual_seed(42)\nclass TN(nn.Module):\n    def __init__(self, act):\n        super().__init__()\n        self.f1=nn.Linear(10,10); self.f2=nn.Linear(10,10); self.act=act\n    def forward(self,x):\n        x=self.act(self.f1(x)); return self.act(self.f2(x)).sum()\nx = -torch.randn(1,10)\nprint(f"输入范围: [{x.min():.2f}, {x.max():.2f}] — 全是负数!")\nprint()\nfor name, act in [("ReLU",nn.ReLU()),("Swish",nn.SiLU())]:\n    m=TN(act); m(x).backward(); gn=m.f1.weight.grad.norm().item()\n    print(f"{name}: fc1 梯度范数 = {gn:.6f}")\n    print(f"  -> {'DEAD! 无法学习!' if gn==0 else 'Alive! 可以继续学习'}")\n    print()'))

C.append(M('---\n## 5. Roofline Model\n\n计算强度 = FLOPs / Bytes。A100 拐点 ~150 FLOPs/Byte。<150 = memory-bound, >150 = compute-bound。Qwen3 Q投影: B=1 时 memory-bound, B=512 时 compute-bound。'))
C.append(K('def flops(M,N,K): return 2*M*N*K\ndef mem(M,N,K,b=4): return (M*K+K*N+M*N)*b\ndef ai(M,N,K,b=4): return flops(M,N,K)/mem(M,N,K,b)\nprint("Qwen3 Q-proj [B,1024]x[1024,2048] (FP16):")\nprint(f"  {"B":<8} {"MFLOPs":<10} {"MB":<10} {"AI":<8} {"Type"}")\nfor B in [1,4,32,256,512]:\n    a=ai(B,2048,1024,2)\n    bn="Compute-bound" if a>150 else "Memory-bound"\n    print(f"  {B:<8} {flops(B,2048,1024)/1e6:>8.1f} {mem(B,2048,1024,2)/1e6:>8.1f} {a:>6.1f}   {bn}")\nprint("\\nA100 roofline knee ~150 FLOPs/Byte")\nprint("Decode (B=1): Memory-bound | Prefill (B=512): Compute-bound")'))

C.append(K('fig,ax=plt.subplots(figsize=(10,6))\nai_r=np.logspace(-1,3,1000)\nax.loglog(ai_r,np.minimum(np.full_like(ai_r,312),2.039*ai_r),"k-",lw=2)\nax.fill_between(ai_r,2.039*ai_r,alpha=0.1,color="red")\nax.fill_between(ai_r,np.full_like(ai_r,312),alpha=0.1,color="blue")\nops={"Add":(0.25,10,"red"),"RMSNorm":(0.5,15,"red"),"Q(B=1)":(0.5,50,"orange"),"SDPA Dec":(0.02,5,"red"),"Q(B=256)":(150,280,"green"),"MatMul":(200,300,"green")}\nfor n,(a,p,c) in ops.items():\n    ax.scatter([a],[p],s=100,c=c,edgecolors="black",zorder=10)\n    ax.annotate(n,(a,p),textcoords="offset points",xytext=(10,5),fontsize=9)\nax.set_xlabel("Arithmetic Intensity (FLOPs/Byte)",fontsize=13)\nax.set_ylabel("TFLOPS",fontsize=13)\nax.set_title("Roofline - A100 FP16",fontsize=15,fontweight="bold")\nax.text(0.5,220,"Memory-Bound",fontsize=11,color="red")\nax.text(60,220,"Compute-Bound",fontsize=11,color="blue")\nax.grid(True,alpha=0.3,which="both"); plt.tight_layout(); plt.show()'))

C.append(M('---\n## 6. 优化器对比\n\n不良条件函数 f(w1,w2) = w1^2 + 10w2^2。w2方向曲率是w1的10倍。SGD震荡，Momentum平滑，Adam自适应每个参数的学习率。'))
C.append(K('def f(w1,w2): return w1**2+10*w2**2\ndef train(cls,lr,steps=30):\n    w=torch.tensor([8.,8.],requires_grad=True)\n    opt=cls([w],lr=lr)\n    p=[w.detach().clone().numpy()]\n    for _ in range(steps):\n        opt.zero_grad(); f(w[0],w[1]).backward(); opt.step()\n        p.append(w.detach().clone().numpy())\n    return np.array(p)\nfig,axes=plt.subplots(1,3,figsize=(16,4.5))\ncfgs=[\n    ("SGD",torch.optim.SGD,0.02),\n    ("SGD+Momentum",lambda p,lr:torch.optim.SGD(p,lr=lr,momentum=0.9),0.02),\n    ("Adam",torch.optim.Adam,0.3),\n]\nfor ax,(nm,cls,lr) in zip(axes,cfgs):\n    p=train(cls,lr,30)\n    ax.plot(p[:,0],p[:,1],"o-",ms=4,lw=1.5,color="#2196F3")\n    ax.scatter([0],[0],s=200,marker="*",color="red",zorder=10,edgecolors="black")\n    ax.set_xlim(-10,10); ax.set_ylim(-10,10)\n    ax.set_xlabel("w1"); ax.set_ylabel("w2")\n    ax.set_title(nm + "\\n" + f"lr={lr}",fontweight="bold")\n    ax.grid(True,alpha=0.3)\nplt.suptitle("Optimizer Paths: f(w1,w2)=w1^2+10w2^2",fontsize=14,fontweight="bold")\nplt.tight_layout(); plt.show()\nprint("SGD: 震荡 | Momentum: 平滑 | Adam: 最快")'))

C.append(M('---\n## 7. 学习率调度\n\nWarmup + Cosine：LLM 训练标配。前 N 步线性增长 (防梯度爆炸)，之后余弦衰减 (精细收敛)。'))
C.append(K('def wcos(step,warm,tot,lrmax=1e-3,lrmin=1e-5):\n    if step<warm: return lrmax*step/warm\n    p=(step-warm)/(tot-warm)\n    return lrmin+0.5*(lrmax-lrmin)*(1+np.cos(np.pi*p))\nlrs=[wcos(s,100,1000) for s in range(1000)]\nplt.figure(figsize=(12,4))\nplt.plot(lrs,lw=2,color="#2196F3")\nplt.axvline(x=100,color="red",ls="--",label="Warmup end (step 100)")\nplt.xlabel("Step",fontsize=13); plt.ylabel("LR",fontsize=13)\nplt.title("Warmup + Cosine Annealing",fontsize=15,fontweight="bold")\nplt.legend(fontsize=12); plt.grid(True,alpha=0.3)\nplt.tight_layout(); plt.show()\nprint("前100步: lr 从0线性增长到 0.001")\nprint("后900步: lr 余弦衰减到 0.00001")'))

C.append(M('---\n## 8. SIMD\n\nPython loop (模拟标量) vs NumPy 向量化 (底层 SIMD)。AVX-512 一次 16 个 FP32，GPU warp 同时 32 线程。'))
C.append(K('import time\nN=10_000_000\na=np.random.randn(N).astype(np.float32)\nb=np.random.randn(N).astype(np.float32)\nt0=time.time()\ncs=np.zeros(N,np.float32)\nfor i in range(min(N,100000)): cs[i]=a[i]+b[i]\nst=time.time()-t0; sns=st/100000*1e9\nt0=time.time(); cv=a+b; vt=time.time()-t0; vns=vt/N*1e9\nprint(f"Python loop: {st*1000:.1f}ms/100K -> {sns:.1f}ns/elem")\nprint(f"NumPy vec:   {vt*1000:.1f}ms/{N//1_000_000}M -> {vns:.2f}ns/elem")\nprint(f"Speedup: ~{sns/vns:.0f}x")\nprint()\nprint("CPU AVX-512: 16 FP32/instruction")\nprint("GPU warp:    32 threads in parallel")\nprint("SIMD/SIMT = parallelism = free performance")'))

C.append(M('---\n## Summary\n\n| Concept | Experiment | Key Insight |\n|---------|-----------|------------|\n| Broadcasting | pos/neg examples | align from right, equal or 1 |\n| Activations | 6 curves + negative compare | Swish/GELU > ReLU in negative |\n| Softmax | Temperature experiment | T<1 sharper, T>1 smoother |\n| SwiGLU | handwritten mini impl | gate * up = selective gating |\n| Normalization | handwritten BN/LN/RMS | RMSNorm saves 30% compute |\n| Gradient | manual SGD vs autograd | gradient = direction, lr = step |\n| Dead ReLU | all-negative input | Swish alive, ReLU dead |\n| Roofline | FLOPs vs bandwidth | B=1 memory-bound, B=512 compute-bound |\n| Optimizers | ill-conditioned function | Adam adapts per-parameter |\n| LR Schedule | Warmup+Cosine curve | LLM training standard |\n| SIMD | loop vs vectorized | parallelism = free performance |'))

nb.cells = C
nbf.write(nb, "123.ipynb")
print(f"OK - {len(nb.cells)} cells written")
